### ISSUE TITLE
https unterstützung

### ISSUE THREAD

**Issue by Butterkeks1000** [LeonardNolting/umdiewelt#40]
Es hat zwar nicht direkt was mit dem Code der Webseite zu tun, aber wäre es nicht ganz gut TLS einzurichten, gerade wenn viele Leute die Seite aktuell besuchen?

**Comment by LeonardNolting** [comment]
habe ich schon vor längerer Zeit mal gefragt, wegen http/2 Ladezeiten (s. lighthouse-Bericht für mobile) und brotli compression (etwa -20% ggb. gzip), ist aber leider laut Herrn Sesselmann nicht einfach für die subdomain einzurichten..
![image](https://user-images.githubusercontent.com/49598438/168250777-1a4ea55d-1df7-40b1-aa8d-0fdd7d30ffe2.png)
